#!/usr/bin/env node

import { mkdir, readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import {
  canonicalJson,
  contrastReport,
  loadAndValidate,
  packageRoot,
  repoRoot,
  resolveAll,
  sha256,
  toCssValue,
  tokenIdToCssName,
} from "./lib.mjs";

const mode = process.argv[2];
if (!new Set(["--check", "--write"]).has(mode)) {
  throw new Error("Usage: node scripts/generate.mjs --check|--write");
}

const { source, tokensById } = await loadAndValidate({
  requireCanonicalSourceBytes: true,
});

function themeBlock(selector, theme) {
  const lines = [
    `${selector} {`,
    `  color-scheme: ${theme === "DARK" ? "dark" : "light"};`,
  ];
  for (const token of resolveAll(source, tokensById, theme)) {
    const cssValue = token.id.startsWith("semantic.typography.tracking.")
      ? `${token.resolved}em`
      : toCssValue(token.type, token.resolved);
    const normalized = cssValue
      .replace(/#[0-9A-F]{3,8}\b/g, (value) => value.toLowerCase())
      .replace(/\b(0\.\d*?[1-9])0+\b/g, "$1")
      .replace(/\b0\.0+\b/g, "0");
    const property = tokenIdToCssName(token.id);
    const declaration = `  ${property}: ${normalized};`;
    if (declaration.length <= 80) {
      lines.push(declaration);
    } else {
      const parts = normalized.split(", ");
      if (parts.length === 1) {
        lines.push(`  ${property}:`, `    ${normalized};`);
      } else {
        lines.push(`  ${property}:`);
        let current = "    ";
        for (const [index, part] of parts.entries()) {
          const suffix = index === parts.length - 1 ? ";" : ",";
          const candidate = `${current}${part}${suffix}`;
          if (current !== "    " && candidate.length > 80) {
            lines.push(current.trimEnd());
            current = `    ${part}${suffix}${index === parts.length - 1 ? "" : " "}`;
          } else {
            current = `${current}${part}${suffix}${index === parts.length - 1 ? "" : " "}`;
          }
        }
        lines.push(current.trimEnd());
      }
    }
  }
  for (const alias of source.meta.compatibilityAliases) {
    lines.push(`  ${alias.cssName}: var(${tokenIdToCssName(alias.target)});`);
  }
  lines.push("}");
  return lines.join("\n");
}

const forcedColors = `@media (forced-colors: active) {
  :root,
  [data-theme="dark"],
  [data-theme="light"] {
    --hp-semantic-color-action-primary: ButtonFace;
    --hp-semantic-color-action-primary-active: ButtonFace;
    --hp-semantic-color-action-primary-hover: ButtonFace;
    --hp-semantic-color-action-secondary: ButtonFace;
    --hp-semantic-color-background-base: Canvas;
    --hp-semantic-color-background-elevated: Canvas;
    --hp-semantic-color-background-subtle: Canvas;
    --hp-semantic-color-background-surface: Canvas;
    --hp-semantic-color-border-emphasis: ButtonText;
    --hp-semantic-color-capability-research-required: CanvasText;
    --hp-semantic-color-capability-unsupported: CanvasText;
    --hp-semantic-color-capability-unverified: CanvasText;
    --hp-semantic-color-focus-ring: Highlight;
    --hp-semantic-color-quality-crossed: CanvasText;
    --hp-semantic-color-quality-gapped: CanvasText;
    --hp-semantic-color-quality-invalid: CanvasText;
    --hp-semantic-color-quality-locked: CanvasText;
    --hp-semantic-color-quality-reconnecting: CanvasText;
    --hp-semantic-color-quality-stale: CanvasText;
    --hp-semantic-color-status-critical: MarkText;
    --hp-semantic-color-status-disabled: GrayText;
    --hp-semantic-color-status-warning: MarkText;
    --hp-semantic-color-surface-interactive: Canvas;
    --hp-semantic-color-surface-selected: Highlight;
    --hp-semantic-color-text-disabled: GrayText;
    --hp-semantic-color-text-inverse: ButtonText;
    --hp-semantic-color-text-link: LinkText;
    --hp-semantic-color-text-primary: CanvasText;
    --hp-semantic-color-text-secondary: CanvasText;
  }

  a {
    text-decoration: underline;
  }

  .prototype-notice {
    border-color: MarkText;
    background: Mark;
    color: MarkText;
  }

  :focus-visible {
    outline: 2px solid Highlight;
    outline-offset: 2px;
    box-shadow: 0 0 0 2px Canvas;
  }
}

@media (prefers-reduced-motion: reduce) {
  :root,
  [data-theme="dark"],
  [data-theme="light"] {
    --hp-semantic-motion-duration-emphasis: 0ms;
    --hp-semantic-motion-duration-fast: 0ms;
    --hp-semantic-motion-duration-panel: 0ms;
    --hp-semantic-motion-duration-standard: 0ms;
  }
}`;

const css = `${[
  "/* Generated by @arbitrage/design-tokens. Do not edit. */",
  themeBlock(":root", "DARK"),
  themeBlock('[data-theme="dark"]', "DARK"),
  themeBlock('[data-theme="light"]', "LIGHT"),
  forcedColors,
].join("\n\n")}\n`;

const contrast = contrastReport(source, tokensById);
if (contrast.some((row) => !row.pass)) {
  throw new Error("CONTRAST_VALIDATION_FAILED");
}

const resolvedDark = new Map(
  resolveAll(source, tokensById, "DARK").map((token) => [
    token.id,
    token.resolved,
  ]),
);
const resolvedLight = new Map(
  resolveAll(source, tokensById, "LIGHT").map((token) => [
    token.id,
    token.resolved,
  ]),
);
const tsPayload = {
  namespace: source.meta.namespace,
  schemaVersion: source.meta.schemaVersion,
  tokenSetVersion: source.meta.tokenSetVersion,
  generatorContractVersion: source.meta.generatorContractVersion,
  defaultTheme: source.meta.defaultTheme,
  resolvedThemes: source.meta.resolvedThemes,
  preferenceModes: source.meta.preferenceModes,
  compatibilityPolicy: source.meta.compatibilityPolicy,
  compatibilityAliases: source.meta.compatibilityAliases,
  tokens: source.tokens.tokens.map((token) => ({
    id: token.id,
    kind: token.kind,
    family: token.family,
    type: token.type,
    accessibilityRole: token.accessibilityRole,
    lifecycle: token.lifecycle,
    dark: resolvedDark.get(token.id),
    light: resolvedLight.get(token.id),
  })),
  chart: source.chart,
  statusPresentations: source.status.presentations,
  forcedColors: source.status.forcedColors,
};
const escapedPayload = JSON.stringify(tsPayload, null, 2)
  .replaceAll("`", "\\`")
  .replaceAll("${", "\\${");
const ts = `/* Generated by @arbitrage/design-tokens. Do not edit. */
export type ResolvedTheme = "DARK" | "LIGHT";
export type PreferenceMode = "SYSTEM" | ResolvedTheme;
export type CanonicalTokenId = string;

export interface ChartSeriesValue {
  readonly id: string;
  readonly marker: string;
  readonly dash: string;
  readonly light: string;
  readonly dark: string;
}

interface DesignTokenMetadata {
  readonly namespace: string;
  readonly schemaVersion: string;
  readonly tokenSetVersion: string;
  readonly generatorContractVersion: string;
  readonly defaultTheme: ResolvedTheme;
  readonly resolvedThemes: readonly ResolvedTheme[];
  readonly preferenceModes: readonly PreferenceMode[];
  readonly compatibilityPolicy: Readonly<Record<string, unknown>>;
  readonly compatibilityAliases: readonly Readonly<Record<string, string>>[];
  readonly tokens: readonly Readonly<Record<string, unknown>>[];
  readonly chart: {
    readonly capacity: number;
    readonly overflowError: "CHART_SERIES_CAPACITY_EXCEEDED";
    readonly categorical: readonly ChartSeriesValue[];
    readonly [key: string]: unknown;
  };
  readonly statusPresentations: readonly Readonly<Record<string, unknown>>[];
  readonly forcedColors: readonly Readonly<Record<string, unknown>>[];
}

const designTokensJson = String.raw\`${escapedPayload}\`;

export const designTokens = JSON.parse(designTokensJson) as DesignTokenMetadata;

export type ChartSeriesResult =
  | { readonly ok: true; readonly value: ChartSeriesValue }
  | {
      readonly ok: false;
      readonly error: "CHART_SERIES_CAPACITY_EXCEEDED";
    };

export function getCategoricalSeries(index: number): ChartSeriesResult {
  if (
    !Number.isInteger(index) ||
    index < 1 ||
    index > designTokens.chart.capacity
  ) {
    return { ok: false, error: designTokens.chart.overflowError };
  }
  return { ok: true, value: designTokens.chart.categorical[index - 1]! };
}
`;

const artifactBytes = Buffer.byteLength(css) + Buffer.byteLength(ts);
if (
  Buffer.byteLength(css) > source.meta.bounds.maxArtifactFileBytes ||
  Buffer.byteLength(ts) > source.meta.bounds.maxArtifactFileBytes ||
  artifactBytes > source.meta.bounds.maxArtifactAggregateBytes
) {
  throw new Error("GENERATED_ARTIFACT_BOUND_EXCEEDED");
}

const cssPath = resolve(packageRoot, "generated/tokens.css");
const tsPath = resolve(packageRoot, "generated/tokens.generated.ts");
const manifestPath = resolve(packageRoot, "generated/tokens.manifest.json");

const digestPaths = [
  ...source.meta.canonicalSources,
  ...source.meta.generatedArtifacts,
].sort();
const generatedBytes = new Map([
  ["packages/design-tokens/generated/tokens.css", Buffer.from(css)],
  ["packages/design-tokens/generated/tokens.generated.ts", Buffer.from(ts)],
]);

async function makeManifest() {
  const digests = [];
  for (const path of digestPaths) {
    const bytes =
      generatedBytes.get(path) ?? (await readFile(resolve(repoRoot, path)));
    digests.push({ path, sha256: sha256(bytes) });
  }
  return canonicalJson({
    namespace: source.meta.namespace,
    schemaVersion: source.meta.schemaVersion,
    tokenSetVersion: source.meta.tokenSetVersion,
    generatorContractVersion: source.meta.generatorContractVersion,
    algorithm: "SHA-256",
    selfHashExcluded: true,
    digests,
  });
}

const manifest = await makeManifest();

async function assertEqual(path, expected) {
  let actual;
  try {
    actual = await readFile(path, "utf8");
  } catch {
    throw new Error(`ARTIFACT_MISSING ${path}`);
  }
  if (actual !== expected) throw new Error(`ARTIFACT_DRIFT ${path}`);
}

if (mode === "--write") {
  await mkdir(resolve(packageRoot, "generated"), { recursive: true });
  await writeFile(cssPath, css);
  await writeFile(tsPath, ts);
  await writeFile(manifestPath, manifest);
  process.stdout.write("D1 artifacts generated deterministically.\n");
} else {
  await assertEqual(cssPath, css);
  await assertEqual(tsPath, ts);
  await assertEqual(manifestPath, manifest);
  process.stdout.write("D1 artifacts match canonical sources.\n");
}
