import assert from "node:assert/strict";
import { execFileSync, spawnSync } from "node:child_process";
import { cp, mkdir, mkdtemp, readFile, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import test from "node:test";
import { fileURLToPath } from "node:url";
import { sha256 } from "../scripts/lib.mjs";

const packageRoot = resolve(fileURLToPath(new URL("..", import.meta.url)));
const generator = resolve(packageRoot, "scripts/generate.mjs");

test("committed artifacts pass deterministic drift check", () => {
  assert.doesNotThrow(() =>
    execFileSync(process.execPath, [generator, "--check"], {
      cwd: resolve(packageRoot, "../.."),
      stdio: "pipe",
    }),
  );
});

test("repeated generation is byte-identical", async () => {
  const paths = [
    "generated/tokens.css",
    "generated/tokens.generated.ts",
    "generated/tokens.manifest.json",
  ];
  execFileSync(process.execPath, [generator, "--write"], {
    cwd: resolve(packageRoot, "../.."),
    stdio: "pipe",
  });
  const first = await Promise.all(
    paths.map(async (path) =>
      sha256(await readFile(resolve(packageRoot, path))),
    ),
  );
  execFileSync(process.execPath, [generator, "--write"], {
    cwd: resolve(packageRoot, "../.."),
    stdio: "pipe",
  });
  const second = await Promise.all(
    paths.map(async (path) =>
      sha256(await readFile(resolve(packageRoot, path))),
    ),
  );
  assert.deepEqual(second, first);
});

test("clean-directory regeneration reproduces artifacts", async () => {
  const directory = await mkdtemp(join(tmpdir(), "d1-clean-"));
  const copyRoot = join(directory, "packages/design-tokens");
  await mkdir(resolve(copyRoot, ".."), { recursive: true });
  await cp(packageRoot, copyRoot, { recursive: true });
  execFileSync(
    process.execPath,
    [resolve(copyRoot, "scripts/generate.mjs"), "--write"],
    { cwd: directory, stdio: "pipe" },
  );
  for (const path of [
    "tokens.css",
    "tokens.generated.ts",
    "tokens.manifest.json",
  ]) {
    assert.equal(
      sha256(await readFile(resolve(copyRoot, "generated", path))),
      sha256(await readFile(resolve(packageRoot, "generated", path))),
    );
  }
});

test("artifact drift is rejected", async () => {
  const directory = await mkdtemp(join(tmpdir(), "d1-drift-"));
  const copyRoot = join(directory, "packages/design-tokens");
  await mkdir(resolve(copyRoot, ".."), { recursive: true });
  await cp(packageRoot, copyRoot, { recursive: true });
  await writeFile(resolve(copyRoot, "generated/tokens.css"), "tampered\n");
  const result = spawnSync(
    process.execPath,
    [resolve(copyRoot, "scripts/generate.mjs"), "--check"],
    { cwd: directory, encoding: "utf8" },
  );
  assert.notEqual(result.status, 0);
  assert.match(result.stderr, /ARTIFACT_DRIFT/);
});

test("manifest hashes exact source and generated bytes and excludes itself", async () => {
  const manifest = JSON.parse(
    await readFile(
      resolve(packageRoot, "generated/tokens.manifest.json"),
      "utf8",
    ),
  );
  assert.equal(manifest.selfHashExcluded, true);
  assert.ok(
    manifest.digests.every(
      (entry) => !entry.path.endsWith("tokens.manifest.json"),
    ),
  );
  assert.deepEqual(
    [...manifest.digests].sort((a, b) => (a.path < b.path ? -1 : 1)),
    manifest.digests,
  );
  for (const entry of manifest.digests) {
    assert.equal(
      entry.sha256,
      sha256(await readFile(resolve(packageRoot, "../..", entry.path))),
      entry.path,
    );
  }
});

test("generated CSS resolves DARK root and explicit DARK/LIGHT maps only", async () => {
  const css = await readFile(
    resolve(packageRoot, "generated/tokens.css"),
    "utf8",
  );
  assert.match(css, /:root \{\n  color-scheme: dark;/);
  assert.match(css, /\[data-theme="dark"\] \{/);
  assert.match(css, /\[data-theme="light"\] \{/);
  assert.doesNotMatch(css, /prefers-color-scheme/);
  assert.doesNotMatch(css, /forced-color-adjust:\s*none/);
});

test("generated TypeScript chart metadata types match emitted runtime tuples", async () => {
  const generated = await readFile(
    resolve(packageRoot, "generated/tokens.generated.ts"),
    "utf8",
  );
  assert.match(generated, /readonly dash: string;/);
  assert.match(generated, /readonly light: string;/);
  assert.match(generated, /readonly dark: string;/);
  assert.doesNotMatch(generated, /readonly dash: readonly number\[\];/);
  assert.doesNotMatch(generated, /readonly color:/);
});

test("initial rollback payload is self-contained and does not require Git history", async () => {
  const bundle = JSON.parse(
    await readFile(
      resolve(packageRoot, "fixtures/initial-rollback.bundle.json"),
      "utf8",
    ),
  );
  assert.equal(bundle.canonicalSetRemoved, true);
  assert.match(bundle.source, /no Git history required/);
  assert.deepEqual(
    bundle.files.map((file) => file.path),
    [
      "packages/design-tokens/tokens.css",
      "packages/design-tokens/package.json",
      "apps/web/src/app/globals.css",
    ],
  );
  for (const file of bundle.files) {
    const bytes = Buffer.from(file.content, file.encoding);
    assert.equal(sha256(bytes), file.sha256, file.path);
  }
});

test("generated artifacts contain no timestamps, machine paths, URLs or secrets", async () => {
  const content = `${await readFile(resolve(packageRoot, "generated/tokens.css"), "utf8")}\n${await readFile(resolve(packageRoot, "generated/tokens.generated.ts"), "utf8")}`;
  assert.doesNotMatch(content, /\/Users\/|[A-Z]:\\|https?:\/\//);
  assert.doesNotMatch(content, /api[_-]?key|secret|credential/i);
  assert.doesNotMatch(content, /20\d{2}-\d{2}-\d{2}T/);
});

test("package export points only to committed generated artifacts", async () => {
  const manifest = JSON.parse(
    await readFile(resolve(packageRoot, "package.json"), "utf8"),
  );
  assert.equal(manifest.style, "./generated/tokens.css");
  assert.equal(manifest.exports["./tokens.css"], "./generated/tokens.css");
  assert.equal(manifest.dependencies, undefined);
  assert.equal(manifest.devDependencies, undefined);
});

test("synthetic fixture manifest covers the required D1 failure classes", async () => {
  const manifest = JSON.parse(
    await readFile(resolve(packageRoot, "fixtures/manifest.json"), "utf8"),
  );
  assert.equal(manifest.networkRequired, false);
  assert.ok(manifest.cases.length >= 50);
  assert.equal(
    new Set(manifest.cases.map((item) => item.id)).size,
    manifest.cases.length,
  );
});
